# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  # corne GLP
  - keyboard: corne_glp
    board: nice_nano_v2
    shield: corne_left # nice_oled
    cmake-arg: -DEXTRA_CONF_FILE=../../config/corne_gpl.conf
  - keyboard: corne_glp
    board: nice_nano_v2
    shield: corne_right # nice_oled
    cmake-arg: -DEXTRA_CONF_FILE=../../config/corne_gpl.conf
  - keyboard: corne_mx
    board: nice_nano_v2
    shield: corne_left # nice_oled
    cmake-arg: -DEXTRA_CONF_FILE=../../config/corne_mx.conf
  - keyboard: corne_mx
    board: nice_nano_v2
    shield: corne_right # nice_oled
    cmake-arg: -DEXTRA_CONF_FILE=../../config/corne_mx.conf
  - keyboard: corne_choc
    board: nice_nano_v2
    shield: corne_left # nice_oled
    cmake-arg: -DEXTRA_CONF_FILE=../../config/corne_choc.conf
  - keyboard: corne_choc
    board: nice_nano_v2
    shield: corne_right # nice_oled
    cmake-arg: -DEXTRA_CONF_FILE=../../config/corne_choc.conf

  - board: nice_nano_v2
    shield: settings_reset